hmm_path: model/hmm
dict_path: model/lmtool.dic
lm_path: model/lmtool.lm
keyphrase_path: keyphrase.list
init_exec: scripts/init.sh
interaction_timeout: 30

invocations:
    bruce:
      enter: scripts/enter.sh
      ack: scripts/ack.sh
      noop: scripts/noop.sh
      exit: scripts/exit.sh
      voice_params: -v+m2 -s160 -a30 -p40
      commands:
          - name: weather
            sentence:
              - Whats the weather like
              - What is the weather like
              - What the weather like
              - Whats the weather today
              - What is the weather today
              - What the weather today
            must:
              - weather
            should:
              - like
              - what
            must_not:
              - forecast
              - tomorrow
            exec: scripts/cmd_weather_today.sh
          - name: forecast
            sentence:
              - Whats the weather forecast
              - What is the weather forecast
              - What the weather forecast
              - Whats the weather tomorrow
              - What is the weather tomorrow
              - What the weather tomorrow
            must:
              - weather
            should:
              - what
              - forecast
              - tomorrow
            must_not:
              - today
              - like
            exec: scripts/cmd_weather_tomorrow.sh
          - name: moon
            sentence:
              - Hows the moon today
              - How is the moon today
              - Whats the moon status
              - What is the moon status
            must:
              - moon
            should:
              - what
              - how
            must_not:
              - weather
              - like
            exec: scripts/cmd_moon.sh
          - name: calendar
            sentence:
              - Show me calendar
            must:
              - calendar
            should:
              - show
            must_not:
            exec: scripts/cmd_cal.sh
          - name: stocks
            sentence:
              - Show my stocks
            must:
              - stocks
            should:
              - show
            must_not:
            exec: scripts/cmd_stocks.sh
          - name: fortune
            sentence:
              - Tell me fortune for today
              - Tell me a joke
            must:
            should:
              - today
              - joke
              - fortune
            must_not:
            exec: scripts/cmd_fortune.sh
          - name: uptime
            sentence:
              - Show me uptime
            must:
              - uptime
            should:
              - show
            must_not:
            exec: scripts/cmd_uptime.sh
          - name: reboot
            sentence:
              - Reboot now
            must:
              - reboot
              - now
            should:
            must_not:
              - not
            exec: scripts/cmd_reboot.sh
    cybill:
      enter: scripts/enter.sh
      ack: scripts/ack.sh
      noop: scripts/noop.sh
      exit: scripts/exit.sh
      voice_params: -v+f5 -s160 -a30 -p40
      commands:
          - name: weather
            sentence:
              - Whats the weather like
              - What is the weather like
              - What the weather like
              - Whats the weather today
              - What is the weather today
              - What the weather today
            must:
              - weather
            should:
              - like
              - what
            must_not:
              - forecast
              - tomorrow
            exec: scripts/cmd_weather_today.sh
          - name: forecast
            sentence:
              - Whats the weather forecast
              - What is the weather forecast
              - What the weather forecast
              - Whats the weather tomorrow
              - What is the weather tomorrow
              - What the weather tomorrow
            must:
              - weather
            should:
              - what
              - forecast
              - tomorrow
            must_not:
              - today
              - like
            exec: scripts/cmd_weather_tomorrow.sh
          - name: moon
            sentence:
              - Hows the moon today
              - How is the moon today
              - Whats the moon status
              - What is the moon status
            must:
              - moon
            should:
              - what
              - how
            must_not:
              - weather
              - like
            exec: scripts/cmd_moon.sh
          - name: calendar
            sentence:
              - Show me calendar
            must:
              - calendar
            should:
              - show
            must_not:
            exec: scripts/cmd_cal.sh
          - name: stocks
            sentence:
              - Show my stocks
            must:
              - stocks
            should:
              - show
            must_not:
            exec: scripts/cmd_stocks.sh
          - name: fortune
            sentence:
              - Tell me fortune for today
              - Tell me a joke
            must:
            should:
              - today
              - joke
              - fortune
            must_not:
            exec: scripts/cmd_fortune.sh
          - name: uptime
            sentence:
              - Show me uptime
            must:
              - uptime
            should:
              - show
            must_not:
            exec: scripts/cmd_uptime.sh
          - name: reboot
            sentence:
              - Reboot now
            must:
              - reboot
              - now
            should:
            must_not:
              - not
            exec: scripts/cmd_reboot.sh

